### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by jbenet** [ipfs/mgmt#2]
**Sprint Goal** - Produce various demos of using IPFS to ship + boot VMs and containers.

**Sprint Participants** - @whyrusleeping, @dylanPowers, @hosh, @kkoroviev

**Sprint Deliverables**

Each of this items will have a DRI (directly responsible individual).

- [x] Implement a docker registry that uses a local or remote IPFS node (@whyrusleeping)
- [ ] Produce assets for these demos:
  - Prereq: Getting ipfs-docker runnable/compilable
  - [x] https://github.com/jbenet/ipfs-container-demos/issues/1 (@hosh)
  - [x] https://github.com/jbenet/ipfs-container-demos/issues/2 (@hosh)
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/3 (@hosh)
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/4 (@hosh)
    - [ ] Prepare VM that can scale X VMs
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/5 (@hosh)
    - [ ] Blocker: Need to find a copy of VMWare (is it free? open-source?)
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/8 (@jbenet)
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/17 (@whyrusleeping)
    - [ ] Blocker: vm's take forever to add, makes working on this painful

- [ ] Get Blog Ready (@jbenet)
  - [x] Move ipfs-website outside of protocol/websites (@jbenet)
  - [x] Cleanup website generation (@jbenet)
  - [x] Make the blog structure (pick a static blog generator -- likely still metalsmith) (@jbenet)
  - [x] Make the first post (@jbenet)
  - [ ] Publish the blog (@jbenet)

- [ ] Repo Reorg
  - [x] move repos all to ipfs/ (@jbenet)
  - [x] move jbenet/ipfs -> ipfs/ipfs (@jbenet)
  - [x] move papers from jbenet/ipfs -> ipfs/papers (@jbenet)
  - [x] Repository map (with links to everything) (@dylan) 
  
- [ ] Community 
  - [ ] Periodic Newsletter (@dylan)
  - [x] figure out best way to get one board (@dylan)
        (Waffle.io, potentially we need to modify it)

- [ ] Improve IPNS/DHT Reliability (@whyrusleeping)
  - [x] Reduce Bandwidth Usage of DHT (ipfs/go-ipfs#986) (@whyrusleeping)
  - [x] Cache public keys to improve latency (ipfs/go-ipfs#987) (@whyrusleeping)
  - [ ] Collate records received on 'Get' RPC and choose best (@whyrusleeping)
    - [ ] Blocker: waiting on feedback for record validity interface/format

- [ ] Other
  - [x] Bitswap bottleneck investigation (@whyrusleeping)
  - [x] Bandwidth Metrics (ipfs/go-ipfs#969) (@whyrusleeping)
  - [x] rewrite deps after repo move (ipfs/go-ipfs#996) (@hosh)
  - [x] fix fuse file owner permissions (ipfs/go-ipfs#967) (@whyrusleeping)
  - [x] merge mount test PRs (https://github.com/ipfs/go-ipfs/pull/945) (@kkoroviev, @jbenet, @chriscool)
  - [x] dht handler log keys https://github.com/ipfs/go-ipfs/pull/1003 (@jbenet)
  - [x] gobuilder improvements for user friendliness https://github.com/ipfs/go-ipfs/pull/1004 (@jbenet)

### Backlog

- [ ] fix `refs local` bug (ipfs/go-ipfs#994)

- [ ] Implement a tool that achieves `ipfs-docker run <ipfs-path>`
  - [ ] Fix Broken Symlinks (ipfs/go-ipfs#979)

- [ ] Produce videos for these demos:
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/1
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/2
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/3
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/4
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/5
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/6
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/7
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/8
  - [ ] https://github.com/jbenet/ipfs-container-demos/issues/17
